### ISSUE TITLE
Feature02(Point-cambio y z)

### ISSUE THREAD

**Issue by carlos-cb** [carlos-cb/SpaiEcp2BeiChu#2]
Añadir un método a la clase Point que sirva para poder modificar las coordenadas de un punto y añadir una tercera coordenada (z) y hacer todos los métodos con z.
Realizar los test por favor.

**Comment by imolinuevo** [comment]
Funcionalidad añadida, test actualizados y superados.

**Comment by imolinuevo** [comment]
Acaba de verificarlo travis también así que todo perfecto. ;)
