### ISSUE TITLE
Feature04(User-otra forma)

### ISSUE THREAD

**Issue by carlos-cb** [carlos-cb/SpaiEcp2BeiChu#4]
Añadir una nueva funcionalidad a la clase User que presente el nombre del usuario con la primera letra mayúscula, el resto en minúsculas y separados por comas.
Realizar los test por favor.

**Comment by borisjaviervillarreal** [comment]
Realizado y testeado

**Comment by carlos-cb** [comment]
testNombreLowerComas(ecp2test.UserTest)  Time elapsed: 0 sec  <<< ERROR!
Hay un error en el método testNombreLowerComas. Revisalo porfa.

**Comment by sandrach85** [comment]
Este método vuelve a ser de Boris, no mio

**Comment by borisjaviervillarreal** [comment]
corregido y testeado, y ya ha pasado los errores en travis todo correcto
